### ISSUE TITLE
Problem using molecules with no bond (CH4)

### ISSUE THREAD

**Issue by elbarto91** [theplatypus/scott#1]
hello, i am a master thesis student from italy, i'm trying to use your code as part of my project and i found a little issue regarding the molecules with no 'bond', like the methane which is CH4. Infact  in the canonization there is a part that return None if there aren't no bond or node, so if i use your code to canonize this molecule it return a None element.

**Comment by theplatypus** [comment]
Hello,
Thank you for your interest !
Parsers are indeed very simplistic, the good news is that they are simple to fix as well. 
What parser do you use specifically ? Can you provide an example failing file ?

**Comment by elbarto91** [comment]
hello, 
yes I saw it, in fact I tried to adapt them to my project with a positive outcome.
You can see the error using this file https://static.molinstincts.com/sdf_3d/ETHANE-3D-structure-CT1000156871.sdf, the problem is in the '`Mol_to_Graph`' function in parse.py there is a check
```
if not atoms or not bonds:
        return None
```
if  the flag ignore hydrogen is True then the molecule will be represented by a graph with only one node (C) and no bond.
I solved by replacing the `or ` with an  `and` .

**Comment by theplatypus** [comment]
Hello,

Sorry I've been doing something else those last weeks. Your correction is correct, I updated the code according to it, so I'm closing the issue.
I will update the docker containers soon.

I hope this repo helped you in your works. Please let me know if I can help you on something. ;)
