### ISSUE TITLE
Error when creating adjacency matrix of simple graph

### ISSUE THREAD

**Issue by janlaub** [theplatypus/scott#4]
Hello!

I am iteratively generating graphs and want to get the adjacency matrix for each one of them. In the beginning, the my graph is very simple (4 nodes that each connect to a fifth central node, no loops). This leads to the list `permut` in `graph.py` line 437 being empty. Thus, the `flatten` function in line 447 throws an out of index error. I fixed this problem by checking if `permut` is empty before calling the `flatten` function.

Thank you for this nice repository!

**Comment by theplatypus** [comment]
Hi, 

Thanks for using this lib and finding that kind of bug! :)
Feel free to emit a PR if you corrected it, otherwise I will gladly do it following your description.

Did you succeed to achieve what you were looking for?
